### PR TITLE
meson: automatic generate LIB_INSTALL_DIR value

### PR DESCRIPTION
**Pull request by alunux**

### CODE REVIEW

**Comment by ilgarmehmetali** [comment]
Thanks for the pull request, i believe budgie doesnt look up /usr/local directory for plugins, so prefix has to be changed to just /usr.
This can be done while running meson, can you also update install instructions in readme file too, it should look like the instructions from "budgie-screenshot-applet"
```
mkdir build && cd build
meson --prefix /usr --buildtype=plain ..
ninja
sudo ninja install
```

**Comment by alunux** [comment]
Well, I'm just not comfortable with that hard coded path.

**Comment by alunux** [comment]
Also, can I replace meson_post_install.sh with meson_post_install.py (look at https://github.com/cybre/budgie-haste-applet/pull/20/files)? We can't do `glib-compile-schemas "/usr/share/glib-2.0/schemas"` in chroot environment when we do packaging, it will give you some problems about permissions because you try to do something with `"/usr/share/glib-2.0/schemas" ` (in system directory, not in chroot directory).

**Comment by ilgarmehmetali** [comment]
Dont get me wrong im fine with this pull request, but this would cause the applet to be not installed in correct directory with current install instructions. Im just asking if you could also change install instructions too.

**Comment by alunux** [comment]
@ilgarmehmetali Done. Can you review it again?

**Comment by ilgarmehmetali** [comment]
LGTM

**Pull request merged**
